### ISSUE TITLE
Export support?

### ISSUE THREAD

**Issue by prologic** [lewispeckover/consulator#8]
Would you consider the addition of an "export" feature and associated command? The idea basically to mirror the `import` facility. Take the contents of Consul and export it as either JSON or YAML.

I'm hesitant to make `sync` a 3-way sync; but if you are open to the above we can explore that layer or just make this a "user problem" to deal with.

**Comment by lewispeckover** [comment]
Hmm, would it add anything over the native [`consul kv export`](https://www.consul.io/docs/commands/kv/export.html)?

**Comment by prologic** [comment]
Hmm tbh I didn't see that `consul` had `consul kv import` and `consul kv export` :D

I have to ask then... What is the purpose of this tool [consulator](https://github.com/lewispeckover/consulator/issues/8) -- Just to handle YAML representation?

**Comment by prologic** [comment]
> Import and synchronize your Consul KV data from JSON and YAML

It seems the native `consul kv import|export` already does this well for JSON right?

**Comment by lewispeckover** [comment]
If you simply want to back up and restore then the native import/export will indeed do the trick.
This tool was created to let you work with a more logical & user-friendly representation of the data.

**Comment by prologic** [comment]
> This tool was created to let you work with a more logical & user-friendly representation of the data

That's precisely how/why I came across this. I want import/export -- But I also want it in a form that's:

* Easy to read for humans
* Easy to manipulate for humans

JSON is "okay" but it gets a bit tedious when you have large quantities of it.

**Comment by prologic** [comment]
So after playing around with various tools to ingest data into Consul, [yq](github.com/mikefarah/yq), [yj](github.com/sclevine/yj) and [consul](github.com/hashicorp/consul) itself I realise consulator doesn't need an `export` at all :) Turns out that `consul kv import` doesn't *quite* import plain 'ol JSON -- So I need to use your nicely written consulator anyway :)
