### ISSUE TITLE
Support for array of objects

### ISSUE THREAD

**Issue by prologic** [lewispeckover/consulator#9]
It looks like consulator doesn't understand hot to import the following:

```#!yaml
config:
  foo:
    rules:
      - foo: bar
        exp:
          type: A
```

You end up with an err rlike:
```
Error: Invalid type map[string]interface {} in array. Only strings, numbers and boolean values are supported.
```

Is this a KP or intentional?

**Comment by prologic** [comment]
I've narrowed it down to array of objects:

Example:

```#!yaml
AAPL:
  - shares: -75.088
    date: 11/27/2015
  - shares: 75.088
    date: 11/26/2015
```

This fails to import.

**Comment by lewispeckover** [comment]
Currently, it's intentionally not supported. 
If it were to be supported, how would you expect it to be represented in Consul?

**Comment by prologic** [comment]
As a tree of key/value(s) of course :) -- My consumer here is [Consul Template](https://github.com/hashicorp/consul-template) and I *was* trying to use the `{{ tree "<prefix>" }}` function but since consulator can't import such things I've opted for:

```#!yaml
config:
  nested_json: |
    <json here>
```

**Comment by lewispeckover** [comment]
What do you mean by a "a tree of key/value(s)"?

What would the structure look like? Are you suggesting it should create a path component from the index of your array, like this?

```
AAPL/0/shares: -75.088
AAPL/0/date: 11/27/2015
AAPL/1/shares: 75.088
AAPL/1/date: 11/26/2015
```
Or something different?

Consul can only store simple values at a given path, so I don't see a logical way to do this...
Sorry if I'm missing something obvious! :slightly_smiling_face:

**Comment by prologic** [comment]
No you are absolutely  right! I don't know what I was thinking :P -- Long day!

It makes no sense to import an array of objects. Thanks for confirming my silliness :D
